sudo: required

services:
  - docker

script:
  - docker build -t quay.io/ukhomeofficedigital/kb8or:travis .
  - docker run -it --rm -v ${PWD}:/var/lib/deploy quay.io/ukhomeofficedigital/kb8or:travis --help
