apiVersion: v1
kind: Service
metadata:
  name: ${env}-my-project
  labels:
    name: my-project
    env: ${env}
    role: service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: ${node_port}
  selector:
    name: ${env}-my-project
