apiVersion: v1
kind: ReplicationController
metadata:
  name: ${env}-my-project
spec:
  replicas: 1
  selector:
    name: ${env}-my-project
  template:
    metadata:
      labels:
        name: ${env}-my-project
        env: ${env}
    spec:
      containers:
      - name: ${env}-my-project
        image: quay.io/ukhomeofficedigital/my-project:set.by.kb8or
        env:
        - name: MY_VARY
          value: ${my_var}
        ports:
        - containerPort: 8080
      - name: ${env}-my-project-nginx
        image: my_user/nginx:v1
        ports:
        - containerPort: 80
