apiVersion: v1
kind: ReplicationController
metadata:
  name: es-template
  labels:
    component: elasticsearch
    role: ${ es_tier }
    Fn::OptionalHashItem: ${ node_selector }
spec:
  replicas: ${ es_replicas }
  selector:
    component: elasticsearch
    role: ${ es_tier }
    Fn::OptionalHashItem: ${ node_selector }
  template:
    metadata:
      labels:
        component: elasticsearch
        role: ${ es_tier }
        Fn::OptionalHashItem: ${ node_selector }
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-${ es_tier }
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/ukhomeofficedigital/elasticsearch:v0.1.0
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "${ es_cluster }"
        - name: NODE_MASTER
          value: "${ es_master }"
        - name: NODE_DATA
          value: "${ es_data }"
        - name: HTTP_ENABLE
          value: "${ es_client }"
        - name: CLOUD_ENABLE
          value: "true"
        ports: ${ es_ports }
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
      nodeSelector: ${ node_selector }